bitbake/lib/toaster/bldviewer/urls.py
#
# BitBake Toaster Implementation
#
# Copyright (C) 2013        Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from django.conf.urls import patterns, include, url
from django.views.generic.simple import redirect_to

urlpatterns = patterns('bldviewer.views',
        url(r'^builds/$', 'build', name='all-builds'),
        url(r'^build/(?P<build_id>\d+)/task/$', 'task', name='task'),
        url(r'^build/(?P<build_id>\d+)/packages/$', 'bpackage', name='bpackage'),
        url(r'^build/(?P<build_id>\d+)/package/(?P<package_id>\d+)/files/$', 'bfile', name='bfile'),
        url(r'^build/(?P<build_id>\d+)/target/(?P<target_id>\d+)/packages/$', 'tpackage', name='tpackage'),
        url(r'^build/(?P<build_id>\d+)/configuration/$', 'configuration', name='configuration'),
        url(r'^layers/$', 'layer', name='all-layers'),
        url(r'^layerversions/(?P<layerversion_id>\d+)/recipes/.*$', 'layer_versions_recipes', name='layer_versions_recipes'),
        url(r'^$', redirect_to, {'url': 'builds/'}),
)

bitbake/lib/toaster/toastermain/urls.py
#
# BitBake Toaster Implementation
#
# Copyright (C) 2013        Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from django.conf.urls import patterns, include, url
from django.views.generic.simple import redirect_to
from django.views.decorators.cache import never_cache


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^simple/', include('bldviewer.urls')),
    url(r'^api/1.0/', include('bldviewer.api')),
    url(r'^gui/', include('toastergui.urls')),
    url(r'^$', never_cache(redirect_to), {'url': '/simple/'}),
    # Examples:
    # url(r'^toaster/', include('toaster.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

bitbake/lib/toaster/orm/models.py
#
# BitBake Toaster Implementation
#
# Copyright (C) 2013        Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class Build(models.Model):
    SUCCEEDED = 0
    FAILED = 1
    IN_PROGRESS = 2

    BUILD_OUTCOME = (
        (SUCCEEDED, 'Succeeded'),
        (FAILED, 'Failed'),
        (IN_PROGRESS, 'In Progress'),
    )

    search_allowed_fields = ['machine',
                             'cooker_log_path']

    machine = models.CharField(max_length=100)
    image_fstypes = models.CharField(max_length=100)
    distro = models.CharField(max_length=100)
    distro_version = models.CharField(max_length=100)
    started_on = models.DateTimeField()
    completed_on = models.DateTimeField()
    outcome = models.IntegerField(choices=BUILD_OUTCOME, default=IN_PROGRESS)
    errors_no = models.IntegerField(default=0)
    warnings_no = models.IntegerField(default=0)
    cooker_log_path = models.CharField(max_length=500)
    build_name = models.CharField(max_length=100)
    bitbake_version = models.CharField(max_length=50)

@python_2_unicode_compatible
class Target(models.Model):
    search_allowed_fields = ['target', 'image_fstypes', 'file_name']
    build = models.ForeignKey(Build)
    target = models.CharField(max_length=100)
    is_image = models.BooleanField(default = False)
    file_name = models.CharField(max_length=100)
    file_size = models.IntegerField()

    def __str__(self):
        return self.target


class Task(models.Model):

    SSTATE_NA = 0
    SSTATE_MISS = 1
    SSTATE_FAILED = 2
    SSTATE_RESTORED = 3

    SSTATE_RESULT = (
        (SSTATE_NA, 'Not Applicable'), # For rest of tasks, but they still need checking.
        (SSTATE_MISS, 'Missing'), # it is a miss
        (SSTATE_FAILED, 'Failed'), # there was a pkg, but the script failed
        (SSTATE_RESTORED, 'Restored'), # succesfully restored
    )

    CODING_PYTHON = 0
    CODING_SHELL = 1

    TASK_CODING = (
        (CODING_PYTHON, 'Python'),
        (CODING_SHELL, 'Shell'),
    )

    OUTCOME_SUCCESS = 0
    OUTCOME_COVERED = 1
    OUTCOME_SSTATE = 2
    OUTCOME_EXISTING = 3
    OUTCOME_FAILED = 4
    OUTCOME_NA = 5

    TASK_OUTCOME = (
        (OUTCOME_SUCCESS, 'Succeeded'),
        (OUTCOME_COVERED, 'Covered'),
        (OUTCOME_SSTATE, 'Sstate'),
        (OUTCOME_EXISTING, 'Existing'),
        (OUTCOME_FAILED, 'Failed'),
        (OUTCOME_NA, 'Not Available'),
    )

    build = models.ForeignKey(Build, related_name='task_build')
    order = models.IntegerField(null=True)
    task_executed = models.BooleanField(default=False) # True means Executed, False means Prebuilt
    outcome = models.IntegerField(choices=TASK_OUTCOME, default=OUTCOME_NA)
    sstate_checksum = models.CharField(max_length=100, blank=True)
    path_to_sstate_obj = models.FilePathField(max_length=500, blank=True)
    recipe = models.ForeignKey('Recipe', related_name='build_recipe')
    task_name = models.CharField(max_length=100)
    source_url = models.FilePathField(max_length=255, blank=True)
    work_directory = models.FilePathField(max_length=255, blank=True)
    script_type = models.IntegerField(choices=TASK_CODING, default=CODING_PYTHON)
    line_number = models.IntegerField(default=0)
    disk_io = models.IntegerField(null=True)
    cpu_usage = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    elapsed_time = models.CharField(max_length=50, default=0)
    sstate_result = models.IntegerField(choices=SSTATE_RESULT, default=SSTATE_NA)
    message = models.CharField(max_length=240)
    logfile = models.FilePathField(max_length=255, blank=True)

    class Meta:
        ordering = ('order', 'recipe' ,)


class Task_Dependency(models.Model):
    task = models.ForeignKey(Task, related_name='task_dependencies_task')
    depends_on = models.ForeignKey(Task, related_name='task_dependencies_depends')


class Build_Package(models.Model):
    build = models.ForeignKey('Build')
    recipe = models.ForeignKey('Recipe', null=True)
    name = models.CharField(max_length=100)
    version = models.CharField(max_length=100, blank=True)
    revision = models.CharField(max_length=32, blank=True)
    summary = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=200, blank=True)
    size = models.IntegerField(default=0)
    section = models.CharField(max_length=80, blank=True)
    license = models.CharField(max_length=80, blank=True)

class Build_Package_Dependency(models.Model):
    TYPE_RDEPENDS = 0
    TYPE_RPROVIDES = 1
    TYPE_RRECOMMENDS = 2
    TYPE_RSUGGESTS = 3
    TYPE_RREPLACES = 4
    TYPE_RCONFLICTS = 5
    DEPENDS_TYPE = (
        (TYPE_RDEPENDS, "rdepends"),
        (TYPE_RPROVIDES, "rprovides"),
        (TYPE_RRECOMMENDS, "rrecommends"),
        (TYPE_RSUGGESTS, "rsuggests"),
        (TYPE_RREPLACES, "rreplaces"),
        (TYPE_RCONFLICTS, "rconflicts"),
    )
    package = models.ForeignKey(Build_Package, related_name='bpackage_dependencies_package')
    depends_on = models.CharField(max_length=100)   # soft dependency
    dep_type = models.IntegerField(choices=DEPENDS_TYPE)


class Target_Package(models.Model):
    target = models.ForeignKey('Target')
    recipe = models.ForeignKey('Recipe', null=True)
    name = models.CharField(max_length=100)
    version = models.CharField(max_length=100, blank=True)
    size = models.IntegerField()


class Target_Package_Dependency(models.Model):
    TYPE_DEPENDS = 0
    TYPE_RDEPENDS = 1
    TYPE_RECOMMENDS = 2

    DEPENDS_TYPE = (
        (TYPE_DEPENDS, "depends"),
        (TYPE_RDEPENDS, "rdepends"),
        (TYPE_RECOMMENDS, "recommends"),
    )
    package = models.ForeignKey(Target_Package, related_name='tpackage_dependencies_package')
    depends_on = models.ForeignKey(Target_Package, related_name='tpackage_dependencies_depends')
    dep_type = models.IntegerField(choices=DEPENDS_TYPE)


class Build_File(models.Model):
    bpackage = models.ForeignKey(Build_Package, related_name='filelist_bpackage')
    path = models.FilePathField(max_length=255, blank=True)
    size = models.IntegerField()

class Target_File(models.Model):
    tpackage = models.ForeignKey(Target_Package, related_name='filelist_tpackage')
    path = models.FilePathField(max_length=255, blank=True)
    size = models.IntegerField()


class Recipe(models.Model):
    name = models.CharField(max_length=100, blank=True)
    version = models.CharField(max_length=100, blank=True)
    layer_version = models.ForeignKey('Layer_Version', related_name='recipe_layer_version')
    summary = models.CharField(max_length=100, blank=True)
    description = models.CharField(max_length=100, blank=True)
    section = models.CharField(max_length=100, blank=True)
    license = models.CharField(max_length=200, blank=True)
    licensing_info = models.TextField(blank=True)
    homepage = models.URLField(blank=True)
    bugtracker = models.URLField(blank=True)
    author = models.CharField(max_length=100, blank=True)
    file_path = models.FilePathField(max_length=255)


class Recipe_Dependency(models.Model):
    TYPE_DEPENDS = 0
    TYPE_RDEPENDS = 1

    DEPENDS_TYPE = (
        (TYPE_DEPENDS, "depends"),
        (TYPE_RDEPENDS, "rdepends"),
    )
    recipe = models.ForeignKey(Recipe, related_name='r_dependencies_recipe')
    depends_on = models.ForeignKey(Recipe, related_name='r_dependencies_depends')
    dep_type = models.IntegerField(choices=DEPENDS_TYPE)

class Layer(models.Model):
    name = models.CharField(max_length=100)
    local_path = models.FilePathField(max_length=255)
    layer_index_url = models.URLField()


class Layer_Version(models.Model):
    layer = models.ForeignKey(Layer, related_name='layer_version_layer')
    branch = models.CharField(max_length=50)
    commit = models.CharField(max_length=100)
    priority = models.IntegerField()


class Variable(models.Model):
    build = models.ForeignKey(Build, related_name='variable_build')
    variable_name = models.CharField(max_length=100)
    variable_value = models.TextField(blank=True)
    file = models.FilePathField(max_length=255)
    changed = models.BooleanField(default=False)
    human_readable_name = models.CharField(max_length=200)
    description = models.TextField(blank=True)


class LogMessage(models.Model):
    INFO = 0
    WARNING = 1
    ERROR = 2

    LOG_LEVEL = ( (INFO, "info"),
            (WARNING, "warn"),
            (ERROR, "error") )

    build = models.ForeignKey(Build)
    level = models.IntegerField(choices=LOG_LEVEL, default=INFO)
    message=models.CharField(max_length=240)
    pathname = models.FilePathField(max_length=255, blank=True)
    lineno = models.IntegerField(null=True)

bitbake/lib/toaster/bldviewer/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Toaster Simple Explorer</title>
<script src="{% static 'js/jquery-2.0.3.js' %}">
</script>
<script src="{% static 'js/bootstrap.js' %}">
</script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
	</head>

<body style="height: 100%">
<div style="width:100%; height: 100%; position:absolute">
<div style="width: 100%; height: 3em" class="nav">
    <ul class="nav nav-tabs">
        <li><a href="{% url all-builds %}">All Builds</a></li>
        <li><a href="{% url all-layers %}">All Layers</a></li>
    </ul>
</div>

<div style="overflow-y:scroll; width: 100%; position: absolute; top: 3em; bottom:70px ">
{% block pagecontent %}
{% endblock %}
</div>
<div class="navbar" style="position: absolute; bottom: 0; width:100%"><br/>About Toaster | Yocto Project </div>
</div>
</body>
</html>

bitbake/lib/toaster/bldviewer/templates/basebuildpage.html
{% extends "basetable.html" %}

{% block pagename %}
<ul class="nav nav-tabs" style="display: inline-block">
  <li><a>Build {{build.target_set.all|join:"&nbsp;"}} at {{build.started_on}} : </a></li>
  <li><a href="{% url task build.id %}"> Tasks </a></li>
  <li><a href="{% url bpackage build.id %}"> Build Packages </a></li>
    {% for t in build.target_set.all %}
        {% if t.is_image %}
  <li><a href="{% url tpackage build.id t.pk %}"> Packages for {{t.target}} </a> </li>
        {% endif %}
    {% endfor %}
  <li><a href="{% url configuration build.id %}"> Configuration </a> </li>
</ul>
     <h1>Toaster - Build {% block pagetitle %} {% endblock %}</h1>
{% endblock %}

bitbake/lib/toaster/bldviewer/templates/basetable.html
{% extends "base.html" %}

{% block pagecontent %}
<script>
function showhideTableColumn(i, sh) {
    if (sh)
        $('td:nth-child('+i+'),th:nth-child('+i+')').show();
    else
        $('td:nth-child('+i+'),th:nth-child('+i+')').hide();
}


function filterTableRows(test) {
    if (test.length > 0) {
        var r = test.split(/[ ,]+/).map(function (e) { return new RegExp(e, 'i') });
        $('tr.data').map( function (i, el) {
            (! r.map(function (j) { return j.test($(el).html())}).reduce(function (c, p) { return c && p;} )) ? $(el).hide() : $(el).show();
        });
    } else
    {
        $('tr.data').show();
    }
}
</script>
<div style="margin-bottom: 0.5em">

    {% block pagename %}
    {% endblock %}
    <div align="left" style="display:inline-block; width: 40%; margin-left: 2em"> Search: <input type="search" id="filterstring" style="width: 80%" onkeyup="filterTableRows($('#filterstring').val())" autocomplete="off">
    </div>
    {% if hideshowcols %}
    <div align="right" style="display: inline-block; width: 40%">Show/Hide columns:
    {% for i in hideshowcols %}
        <span>{{i.name}} <input type="checkbox" id="ct{{i.name}}" onchange="showhideTableColumn({{i.order}}, $('#ct{{i.name}}').is(':checked'))" checked autocomplete="off"></span> |
    {% endfor %}
    </div>
    {% endif %}
</div>
<div>
    <table class="table table-striped table-condensed" style="width:95%">
{% block pagetable %}
{% endblock %}
    </table>
</div>

{% endblock %}

bitbake/lib/toaster/bldviewer/templates/bfile.html
{% extends "basebuildpage.html" %}

{% block pagetitle %}Files for package {{files.0.bpackage.name}} {% endblock %}
{% block pagetable %}
    {% if not files %}
        <p>No files were recorded for this package!</p>
    {% else %}

            <tr>
            <th>Name</th>
            <th>Size (Bytes)</th>
            </tr>

            {% for file in files %}

            <tr class="data">
            <td>{{file.path}}</td>
            <td>{{file.size}}</td>

            {% endfor %}

    {% endif %}

{% endblock %}

bitbake/lib/toaster/bldviewer/templates/bpackage.html
{% extends "basebuildpage.html" %}

{% block pagetitle %}Packages{% endblock %}
{% block pagetable %}
    {% if not packages %}
        <p>No packages were recorded for this target!</p>
    {% else %}

            <tr>
            <th>Name</th>
            <th>Version</th>
            <th>Recipe</th>
            <th>Summary</th>
            <th>Section</th>
            <th>Description</th>
            <th>Size on host disk (KBytes)</th>
            <th>License</th>
            <th>Dependencies List (all)</th>
            </tr>

            {% for package in packages %}

            <tr class="data">
                <td><a name="#{{package.name}}" href="{% url bfile build.pk package.pk %}">{{package.name}} ({{package.filelist_bpackage.count}} files)</a></td>
                <td>{{package.version}}-{{package.revision}}</td>
                <td><a href="{% url layer_versions_recipes package.recipe.layer_version_id %}#{{package.recipe.name}}">{{package.recipe.name}}</a>{{package.package_name}}</a></td>

            <td>{{package.summary}}</td>
            <td>{{package.section}}</td>
            <td>{{package.description}}</td>
            <td>{{package.size}}</td>
            <td>{{package.license}}</td>
            <td>
        <div style="height: 3em; overflow:auto">
            {% for bpd in package.bpackage_dependencies_package.all %}
                {{bpd.dep_type}}: {{bpd.depends_on}} <br/>
            {% endfor %}
        </div>
            </td>
            {% endfor %}

    {% endif %}

{% endblock %}

bitbake/lib/toaster/bldviewer/templates/build.html
{% extends "basetable.html" %}

{% block pagename %}
    <h1>Toaster - Builds</h1>
{% endblock %}

{% block pagetable %}

    {% load projecttags %}
        <tr>
            <th>Outcome</th>
            <th>Started On</th>
            <th>Completed On</th>
            <th>Target</th>
            <th>Machine</th>
            <th>Time</th>
            <th>Errors</th>
            <th>Warnings</th>
            <th>Output</th>
            <th>Log</th>
            <th>Bitbake Version</th>
            <th>Build Name</th>
        </tr>
        {% for build in builds %}
        <tr class="data">
            <td><a href="{% url configuration build.id %}">{{build.get_outcome_display}}</a></td>
            <td>{{build.started_on}}</td>
            <td>{{build.completed_on}}</td>
            <td>{% for t in build.target_set.all %}<a href="{% url tpackage build.id t.id %}">{{t.target}}</a>{% if t.is_image %} (Img){% endif %}<br/>{% endfor %}</td>
            <td>{{build.machine}}</td>
            <td>{% time_difference build.started_on build.completed_on %}</td>
            <td>{{build.errors_no}}:{% if  build.errors_no %}{% for error in logs %}{% if error.build == build %}{% if error.level == 2 %}<p>{{error.message}}</p>{% endif %}{% endif %}{% endfor %}{% else %}None{% endif %}</td>
            <td>{{build.warnings_no}}:{% if  build.warnings_no %}{% for warning in logs %}{% if warning.build == build %}{% if warning.level == 1 %}<p>{{warning.message}}</p>{% endif %}{% endif %}{% endfor %}{% else %}None{% endif %}</td>
            <td>{% if build.outcome == 0 %}{% for t in build.target_set.all %}{% if t.is_image %}{{build.image_fstypes}}{% endif %}{% endfor %}{% endif %}</td>
            <td>{{build.cooker_log_path}}</td>
            <td>{{build.bitbake_version}}</td>
            <td>{{build.build_name}}</td>
        </tr>

        {% endfor %}
{% endblock %}

bitbake/lib/toaster/bldviewer/templates/configuration.html
{% extends "basebuildpage.html" %}

{% block pagetitle %}Configuration{% endblock %}
{% block pagetable %}

            <tr>
            <th>Name</th>
            <th>Value</th>
            <th>Description</th>
            </tr>

            {% for variable in configuration %}

            <tr class="data">
                <td>{{variable.variable_name}}</td>
                <td>{{variable.variable_value}}</td>
                <td>{% if variable.description %}{{variable.description}}{% endif %}</td>
            {% endfor %}

{% endblock %}

bitbake/lib/toaster/bldviewer/templates/layer.html
{% extends "basetable.html" %}

{% block pagename %}
    <h1>Toaster - Layers</h1>
{% endblock %}

{% block pagetable %}
    {% load projecttags %}

        <tr>
            <th>Name</th>
            <th>Local Path</th>
            <th>Layer Index URL</th>
            <th>Known Versions</th>
        </tr>

        {% for layer in layers %}

        <tr class="data">
            <td>{{layer.name}}</td>
            <td>{{layer.local_path}}</td>
            <td><a href='{{layer.layer_index_url}}'>{{layer.layer_index_url}}</a></td>
            <td><table>
            {% for lv in layer.versions %}
                <tr><td>
        <a href="{% url layer_versions_recipes lv.id %}">({{lv.priority}}){{lv.branch}}:{{lv.commit}} ({{lv.count}} recipes)</a>
                </td></tr>
            {% endfor %}
            </table></td>
        </tr>

        {% endfor %}

{% endblock %}

bitbake/lib/toaster/bldviewer/templates/package.html
{% extends "basebuildpage.html" %}

{% block pagetable %}
    {% if not packages %}
        <p>No packages were recorded for this target!</p>
    {% else %}

            <tr>
            <th>Name</th>
            <th>Version</th>
            <th>Size (Bytes)</th>
            <th>Recipe</th>
            <th>Depends on</th>
            </tr>

            {% for package in packages %}

            <tr class="data">
                <td><a name="#{{package.name}}">{{package.name}}</a></td>
                <td>{{package.version}}</td>
                <td>{{package.size}}</td>
                <td><a name="{{package.recipe.name}}.{{package.package_name}}">
                <a href="{% url layer_versions_recipes package.recipe.layer_version_id %}#{{package.recipe.name}}">{{package.recipe.name}}</a>{{package.package_name}}</a></td>
                <td>
            <div style="height: 3em; overflow:auto">
                    {% for d in package.depends_on %}
                    <a href="#{{d.name}}">{{d.name}}</a><br/>
                    {% endfor %}
            </div>
                </td>

            {% endfor %}

    {% endif %}

{% endblock %}

bitbake/lib/toaster/bldviewer/templates/recipe.html
{% extends "basetable.html" %}

{% block pagename %}
<ul class="nav nav-tabs" style="display: inline-block">
  <li><a>Layer  {{layer_version.layer.name}}&nbsp;:&nbsp;{{layer_version.branch}}&nbsp;:&nbsp;{{layer_version.commit}}&nbsp;:&nbsp;{{layer_version.priority}}</a></li>
</ul>
    <h1>Toaster - Recipes for a Layer</h1>
{% endblock %}

{% block pagetable %}
    {% load projecttags %}

        <tr>
        </tr>
            <th>Name</th>
            <th>Version</th>
            <th>Summary</th>
            <th>Description</th>
            <th>Section</th>
            <th>License</th>
            <th>License file</th>
            <th>Homepage</th>
            <th>Bugtracker</th>
            <th>Author</th>
            <th>File_path</th>
            <th style="width: 30em">Recipe Dependency</th>


        {% for recipe in recipes %}

        <tr class="data">
            <td><a name="{{recipe.name}}">{{recipe.name}}</a></td>
            <td>{{recipe.version}}</td>
            <td>{{recipe.summary}}</td>
            <td>{{recipe.description}}</td>
            <td>{{recipe.section}}</td>
            <td>{{recipe.license}}</td>
            <td>{{recipe.licensing_info}}</td>
            <td>{{recipe.homepage}}</td>
            <td>{{recipe.bugtracker}}</td>
            <td>{{recipe.author}}</td>
            <td>{{recipe.file_path}}</td>
            <td>
        <div style="height: 5em; overflow:auto">
            {% for rr in recipe.r_dependencies_recipe.all %}
                <a href="#{{rr.depends_on.name}}">{{rr.depends_on.name}}</a><br/>
            {% endfor %}
        </div>
            </td>
        </tr>

        {% endfor %}

{% endblock %}

bitbake/lib/toaster/bldviewer/templates/task.html
{% extends "basebuildpage.html" %}

{% block pagetitle %}Tasks{% endblock %}
{% block pagetable %}
    {% if not tasks %}
        <p>No tasks were executed in this build!</p>
    {% else %}

            <tr>
            <th>Order</th>
            <th>Task</th>
            <th>Recipe Version</th>
            <th>Task Type</th>
            <th>Checksum</th>
            <th>Outcome</th>
            <th>Message</th>
            <th>Logfile</th>
            <th>Time</th>
            <th>CPU usage</th>
            <th>Disk I/O</th>
            <th>Script type</th>
            <th>File path</th>
            <th>Depends</th>
            </tr>

            {% for task in tasks %}

            <tr class="data">
                <td>{{task.order}}</td>
                <td><a name="{{task.recipe.name}}.{{task.task_name}}">
                <a href="{% url layer_versions_recipes task.recipe.layer_version_id %}#{{task.recipe.name}}">{{task.recipe.name}}</a>.{{task.task_name}}</a></td>
                <td>{{task.recipe.version}}</td>

                {% if task.task_executed %}
                <td>Executed</td>
                {% else %}
                <td>Prebuilt</td>
                {% endif %}

                <td>{{task.sstate_checksum}}</td>
                <td>{{task.get_outcome_display}}{% if task.provider %}</br>(by <a href="#{{task.provider.recipe.name}}.{{task.provider.task_name}}">{{task.provider.recipe.name}}.{{task.provider.task_name}}</a>){% endif %}</td>
                <td><p>{{task.message}}</td>
                <td><a target="_fileview" href="file:///{{task.logfile}}">{{task.logfile}}</a></td>
                <td>{{task.elapsed_time}}</td>
                <td>{{task.cpu_usage}}</td>
                <td>{{task.disk_io}}</td>
                <td>{{task.get_script_type_display}}</td>
                <td><a target="_fileview" href="file:///{{task.recipe.file_path}}">{{task.recipe.file_path}}</a></td>
                <td>
            <div style="height: 3em; overflow:auto">
                {% for tt in task.task_dependencies_task.all %}
                    <a href="#{{tt.depends_on.recipe.name}}.{{tt.depends_on.task_name}}">
                    {{tt.depends_on.recipe.name}}.{{tt.depends_on.task_name}}</a><br/>
                {% endfor %}
            </div>
                </td>
                </tr>

            {% endfor %}

    {% endif %}

{% endblock %}